<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="2" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-09-13T13:20:22 MSK" name="Default suite" finished-at="2022-09-13T13:20:22 MSK" duration-ms="669">
    <groups>
    </groups>
    <test started-at="2022-09-13T13:20:22 MSK" name="Default test" finished-at="2022-09-13T13:20:22 MSK" duration-ms="669">
      <class name="cdsosobist.connectors.rest.ZUP3TestNGClient">
        <test-method is-config="true" signature="setUp()[pri:0, instance:cdsosobist.connectors.rest.ZUP3TestNGClient@20ccf40b]" started-at="2022-09-13T13:20:22 MSK" name="setUp" finished-at="2022-09-13T13:20:22 MSK" duration-ms="536" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testAll()[pri:0, instance:cdsosobist.connectors.rest.ZUP3TestNGClient@20ccf40b]" started-at="2022-09-13T13:20:22 MSK" name="testAll" finished-at="2022-09-13T13:20:22 MSK" duration-ms="72" status="FAIL">
          <exception class="org.identityconnectors.framework.common.exceptions.ConnectorIOException">
            <message>
              <![CDATA[Этот хост неизвестен (test-odata1c01.cds.spb)]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.identityconnectors.framework.common.exceptions.ConnectorIOException: Этот хост неизвестен (test-odata1c01.cds.spb)
at com.evolveum.polygon.rest.AbstractRestConnector.execute(AbstractRestConnector.java:174)
at cdsosobist.connectors.rest.zup3Connector.callRequest(zup3Connector.java:824)
at cdsosobist.connectors.rest.zup3Connector.handleMainJobs(zup3Connector.java:1847)
at cdsosobist.connectors.rest.zup3Connector.executeQuery(zup3Connector.java:1074)
at cdsosobist.connectors.rest.ZUP3TestNGClient.testAll(ZUP3TestNGClient.java:73)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.net.UnknownHostException: Этот хост неизвестен (test-odata1c01.cds.spb)
at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:933)
at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1519)
at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:852)
at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1367)
at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1301)
at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
at com.evolveum.polygon.rest.AbstractRestConnector.execute(AbstractRestConnector.java:172)
... 32 more
]]>
            </full-stacktrace>
          </exception> <!-- org.identityconnectors.framework.common.exceptions.ConnectorIOException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAll -->
      </class> <!-- cdsosobist.connectors.rest.ZUP3TestNGClient -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
